name: testing

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true
        default: '1.0.0'
        type: string
      changelog:
        description: 'Changelog'
        required: true
        default: ''
        type: string
        
jobs: 
  build_ipk:
    permissions:
      contents: write
    name: Build IPK
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release:
          - 21.02.7
          - 23.05.0
        arch:
          - x86_64
          
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: master
          - name: Get node-empty
        run: |
          git clone https://github.com/sbwml/node-empty
      - name: Init build dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo swapoff -a
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install clang-15 llvm-15
          latest_commit="$(curl -s https://api.github.com/repos/daeuniverse/daed/commits/main | jq -r '.sha' | cut -b 1-7)"
          timestamp=$(curl -s https://api.github.com/repos/daeuniverse/daed/commits/main | jq -r '.commit.author.date')
          formatted_timestamp=$(date --date="$timestamp" "+%Y-%m-%d")
          echo "version=$formatted_timestamp-$latest_commit" >> "$GITHUB_ENV"

      - name: Preparing IPK
        run: |
              echo ""
              git clone https://github.com/Houjie80/luci-app-daed
              mkdir feeds artifacts
              cp -rf ./luci-app-daed ./feeds
        
      - name: Building IPK
        uses: Houjie80/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.release }}
          ARTIFACTS_DIR: ${{ github.workspace }}/artifacts
          FEED_DIR: ${{ github.workspace }}/feeds
          PACKAGES: luci-app-daed
          NO_SHFMT_CHECK: 1
        
      - name: Delivering Package
        uses: actions/upload-artifact@v3
        with:
          name: luci-app-daed-${{ matrix.release }}_${{ matrix.arch }}
          path: ${{ github.workspace }}/artifacts/bin/packages/${{ matrix.arch }}/action/luci-app-droidnet*

  push_packages:
    needs: build_ipk
    name: Push Packages to Release
    permissions:
      contents: write  # To push a branch
    runs-on: ubuntu-latest
    steps:
      - name: Download temporary artifact
        uses: actions/download-artifact@v3
        
      - name: Moving artifact to releases
        shell: bash
        run: |
          mkdir ./release
          cp -rf ./luci-app-daed-21.02.7_x86_64/* ./release/luci-app-daed_${{ inputs.version }}_all_21_02.ipk
          cp -rf ./luci-app-daed-23.05.0_x86_64/* ./release/luci-app-daed_${{ inputs.version }}_all_23_05.ipk
  
      - name: Upload release asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./release/*
          overwrite: true
          tag: ${{ inputs.version }}
          file_glob: true
          body: |
            # LUCI APP DROIDNET ${{ inputs.version }}
            droidnet
            ### Information
            - Changelog : 
              - ${{ inputs.changelog }}
